Algoritmo "exercicio1"
var
 n1,n2,soma,diferenca,produto,media:real
inicio
escreval ("Entre com o primeiro numero:")
leia (n1)
escreval("Entre com o segundo numero:")
leia (n2)
 soma <-n1+n2
escreval ("soma:", soma)
 diferenca <- n1-n2
escreval ("diferenca:", diferenca)
  produto <- n1*n2
escreval ("produto:", produto)
 media <- ((n1+n2) + (n1-n2) + (n1*n2))/3
  escreval ("media:", media)
 leia (media)
Fimalgoritmo

